/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-10-03 12:46:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.billing;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.syos.domain.model.Bill;
import com.syos.domain.model.User;
import com.syos.domain.model.User;
import com.syos.domain.model.Employee;
import com.syos.domain.model.Customer;

public final class bills_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/common/footer.jsp", Long.valueOf(1759490927936L));
    _jspx_dependants.put("/WEB-INF/jsp/common/header.jsp", Long.valueOf(1759492388617L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.syos.domain.model.Employee");
    _jspx_imports_classes.add("com.syos.domain.model.Customer");
    _jspx_imports_classes.add("com.syos.domain.model.Bill");
    _jspx_imports_classes.add("com.syos.domain.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Check authentication and role
    User user = (User) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect(request.getContextPath() + "/login.jsp");
        return;
    }

    String userRole = (String) session.getAttribute("userRole");
    if (!"ADMIN".equals(userRole) && !"STAFF".equals(userRole)) {
        response.sendRedirect(request.getContextPath() + "/index.jsp");
        return;
    }

    request.setAttribute("pageTitle", "Bill History - POS");

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>SYOS - ");
      out.print( request.getAttribute("pageTitle") != null ? request.getAttribute("pageTitle") : "Supermarket Billing System" );
      out.write("</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print( request.getContextPath() );
      out.write("/css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

    String firstName = "";
    Object userObj = session.getAttribute("user");
    if (userObj instanceof Employee) {
        firstName = ((Employee) userObj).getFirstName();
    }
    boolean isAdminOrStaff = session.getAttribute("user") != null && ("ADMIN".equals((String) session.getAttribute("userRole")) || "STAFF".equals((String) session.getAttribute("userRole")));

      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\">SYOS</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                ");
 if (session.getAttribute("user") != null) { 
      out.write("\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                            Welcome, ");
      out.print( firstName );
      out.write("\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"userDropdown\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\">Logout</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/login.jsp\">Login</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid mt-3\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <div class=\"col-md-3 col-lg-2 px-0\">\r\n");
      out.write("        <div class=\"sidebar\">\r\n");
      out.write("            <nav class=\"nav flex-column py-3\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/dashboard.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-tachometer-alt me-2\"></i>Dashboard\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/products/list.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-box me-2\"></i>Products\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/inventory/stocks.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-warehouse me-2\"></i>Inventory\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/discounts/list.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-tags me-2\"></i>Discounts\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"nav-link active\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/billing/create-bill.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-cash-register me-2\"></i>Billing\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/reports/daily-sales.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-chart-bar me-2\"></i>Reports\r\n");
      out.write("                </a>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main content -->\r\n");
      out.write("    <div class=\"col-md-9 col-lg-10 main-content\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("            <h2>Bill History</h2>\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/billing/create-bill.jsp\" class=\"btn btn-primary\">\r\n");
      out.write("                <i class=\"fas fa-plus me-2\"></i>Create New Bill\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-header\">\r\n");
      out.write("                <h5 class=\"mb-0\">All Bills</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <div id=\"billsTable\">\r\n");
      out.write("                    <div class=\"text-center py-4\">\r\n");
      out.write("                        <i class=\"fas fa-spinner fa-spin fa-2x mb-2\"></i>\r\n");
      out.write("                        <p>Loading bills...</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    loadBills();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function loadBills() {\r\n");
      out.write("    fetch('");
      out.print( request.getContextPath() );
      out.write("/billing/bills')\r\n");
      out.write("        .then(response => {\r\n");
      out.write("            if (!response.ok) {\r\n");
      out.write("                throw new Error('Failed to load bills');\r\n");
      out.write("            }\r\n");
      out.write("            return response.json();\r\n");
      out.write("        })\r\n");
      out.write("        .then(bills => {\r\n");
      out.write("            displayBills(bills);\r\n");
      out.write("        })\r\n");
      out.write("        .catch(error => {\r\n");
      out.write("            document.getElementById('billsTable').innerHTML = `\r\n");
      out.write("                <div class=\"alert alert-danger\">\r\n");
      out.write("                    <i class=\"fas fa-exclamation-circle me-2\"></i>\r\n");
      out.write("                    Error loading bills: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error.message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            `;\r\n");
      out.write("        });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function displayBills(bills) {\r\n");
      out.write("    const tableDiv = document.getElementById('billsTable');\r\n");
      out.write("\r\n");
      out.write("    if (bills.length === 0) {\r\n");
      out.write("        tableDiv.innerHTML = `\r\n");
      out.write("            <div class=\"text-center py-4 text-muted\">\r\n");
      out.write("                <i class=\"fas fa-receipt fa-2x mb-2\"></i>\r\n");
      out.write("                <p>No bills found</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        `;\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    let html = `\r\n");
      out.write("        <div class=\"table-responsive\">\r\n");
      out.write("            <table class=\"table table-striped\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Serial #</th>\r\n");
      out.write("                        <th>Date</th>\r\n");
      out.write("                        <th>Total Amount</th>\r\n");
      out.write("                        <th>Cash Tendered</th>\r\n");
      out.write("                        <th>Change</th>\r\n");
      out.write("                        <th>Items</th>\r\n");
      out.write("                        <th>Actions</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("    `;\r\n");
      out.write("\r\n");
      out.write("    bills.forEach(bill => {\r\n");
      out.write("        const billDate = new Date(bill.billDate).toLocaleString();\r\n");
      out.write("        html += `\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bill.serialNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${billDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bill.totalAmount.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bill.cashTendered.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bill.changeReturned.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bill.itemCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" items</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <button class=\"btn btn-sm btn-outline-primary\" onclick=\"viewBillDetails(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bill.serialNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">\r\n");
      out.write("                        <i class=\"fas fa-eye\"></i> View\r\n");
      out.write("                    </button>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        `;\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    html += `\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    `;\r\n");
      out.write("\r\n");
      out.write("    tableDiv.innerHTML = html;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function viewBillDetails(serialNumber) {\r\n");
      out.write("    fetch('");
      out.print( request.getContextPath() );
      out.write("/billing/bills/' + serialNumber)\r\n");
      out.write("        .then(response => {\r\n");
      out.write("            if (!response.ok) {\r\n");
      out.write("                throw new Error('Bill not found');\r\n");
      out.write("            }\r\n");
      out.write("            return response.json();\r\n");
      out.write("        })\r\n");
      out.write("        .then(bill => {\r\n");
      out.write("            showBillModal(bill);\r\n");
      out.write("        })\r\n");
      out.write("        .catch(error => {\r\n");
      out.write("            alert('Error loading bill details: ' + error.message);\r\n");
      out.write("        });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showBillModal(bill) {\r\n");
      out.write("    const billDate = new Date(bill.billDate).toLocaleString();\r\n");
      out.write("\r\n");
      out.write("    let itemsHtml = '';\r\n");
      out.write("    if (bill.items && bill.items.length > 0) {\r\n");
      out.write("        bill.items.forEach(item => {\r\n");
      out.write("            itemsHtml += `\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.totalPrice.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    <td>$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.discountAmount.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            `;\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    const modalHtml = `\r\n");
      out.write("        <div class=\"modal fade\" id=\"billModal\" tabindex=\"-1\">\r\n");
      out.write("            <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <h5 class=\"modal-title\">Bill #");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bill.serialNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <strong>Serial Number:</strong> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bill.serialNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <strong>Date:</strong> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${billDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row mb-3\">\r\n");
      out.write("                            <div class=\"col-md-4\">\r\n");
      out.write("                                <strong>Total Amount:</strong> $");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bill.totalAmount.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-4\">\r\n");
      out.write("                                <strong>Cash Tendered:</strong> $");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bill.cashTendered.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-4\">\r\n");
      out.write("                                <strong>Change:</strong> $");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bill.changeReturned.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <h6>Items:</h6>\r\n");
      out.write("                        <div class=\"table-responsive\">\r\n");
      out.write("                            <table class=\"table table-sm\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th>Code</th>\r\n");
      out.write("                                        <th>Name</th>\r\n");
      out.write("                                        <th>Qty</th>\r\n");
      out.write("                                        <th>Total</th>\r\n");
      out.write("                                        <th>Discount</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemsHtml}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-footer\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    `;\r\n");
      out.write("\r\n");
      out.write("    // Remove existing modal if any\r\n");
      out.write("    const existingModal = document.getElementById('billModal');\r\n");
      out.write("    if (existingModal) {\r\n");
      out.write("        existingModal.remove();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    document.body.insertAdjacentHTML('beforeend', modalHtml);\r\n");
      out.write("    const modal = new bootstrap.Modal(document.getElementById('billModal'));\r\n");
      out.write("    modal.show();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    </div> <!-- End container-fluid -->\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"bg-dark text-light mt-5 py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <h5>SYOS</h5>\r\n");
      out.write("                    <p class=\"mb-0\">Supermarket Billing System</p>\r\n");
      out.write("                    <small class=\"text-muted\">Efficient inventory and billing management</small>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-md-end\">\r\n");
      out.write("                    <p class=\"mb-0\">&copy; 2024 SYOS System. All rights reserved.</p>\r\n");
      out.write("                    <small class=\"text-muted\">Version 1.0.0</small>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
