/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2025-10-03 12:48:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.billing;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.syos.domain.model.Product;
import com.syos.domain.model.User;
import com.syos.domain.model.User;
import com.syos.domain.model.Employee;
import com.syos.domain.model.Customer;

public final class create_002dbill_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/common/footer.jsp", Long.valueOf(1759490927936L));
    _jspx_dependants.put("/WEB-INF/jsp/common/header.jsp", Long.valueOf(1759492388617L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.syos.domain.model.Employee");
    _jspx_imports_classes.add("com.syos.domain.model.Customer");
    _jspx_imports_classes.add("com.syos.domain.model.Product");
    _jspx_imports_classes.add("com.syos.domain.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Check authentication and role
    User user = (User) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect(request.getContextPath() + "/login.jsp");
        return;
    }

    String userRole = (String) session.getAttribute("userRole");
    if (!"ADMIN".equals(userRole) && !"STAFF".equals(userRole)) {
        response.sendRedirect(request.getContextPath() + "/index.jsp");
        return;
    }

    request.setAttribute("pageTitle", "Create Bill - POS");

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>SYOS - ");
      out.print( request.getAttribute("pageTitle") != null ? request.getAttribute("pageTitle") : "Supermarket Billing System" );
      out.write("</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.print( request.getContextPath() );
      out.write("/css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

    String firstName = "";
    Object userObj = session.getAttribute("user");
    if (userObj instanceof Employee) {
        firstName = ((Employee) userObj).getFirstName();
    }
    boolean isAdminOrStaff = session.getAttribute("user") != null && ("ADMIN".equals((String) session.getAttribute("userRole")) || "STAFF".equals((String) session.getAttribute("userRole")));

      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.print( request.getContextPath() );
      out.write("/index.jsp\">SYOS</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                ");
 if (session.getAttribute("user") != null) { 
      out.write("\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                            Welcome, ");
      out.print( firstName );
      out.write("\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu dropdown-menu-end\" aria-labelledby=\"userDropdown\">\r\n");
      out.write("                            <li><a class=\"dropdown-item\" href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\">Logout</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                        <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/login.jsp\">Login</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid mt-3\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <div class=\"col-md-3 col-lg-2 px-0\">\r\n");
      out.write("        <div class=\"sidebar\">\r\n");
      out.write("            <nav class=\"nav flex-column py-3\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/dashboard.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-tachometer-alt me-2\"></i>Dashboard\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/products/list.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-box me-2\"></i>Products\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/inventory/stocks.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-warehouse me-2\"></i>Inventory\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/discounts/list.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-tags me-2\"></i>Discounts\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"nav-link active\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/billing/create-bill.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-cash-register me-2\"></i>Billing\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/reports/daily-sales.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-chart-bar me-2\"></i>Reports\r\n");
      out.write("                </a>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main content -->\r\n");
      out.write("    <div class=\"col-md-9 col-lg-10 main-content\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("            <h2>Point of Sale</h2>\r\n");
      out.write("            <div>\r\n");
      out.write("                <button class=\"btn btn-outline-secondary me-2\" onclick=\"clearBill()\">\r\n");
      out.write("                    <i class=\"fas fa-trash me-1\"></i>Clear\r\n");
      out.write("                </button>\r\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/billing/bills.jsp\" class=\"btn btn-outline-info\">\r\n");
      out.write("                    <i class=\"fas fa-list me-1\"></i>View Bills\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- Product Selection -->\r\n");
      out.write("            <div class=\"col-md-8\">\r\n");
      out.write("                <div class=\"card mb-4\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <h5 class=\"mb-0\">Add Products</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("\r\n");
      out.write("                        <div id=\"productResults\">\r\n");
      out.write("                            <div class=\"text-center py-4\">\r\n");
      out.write("                                <i class=\"fas fa-spinner fa-spin fa-2x mb-2\"></i>\r\n");
      out.write("                                <p>Loading products...</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Current Bill Items -->\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <h5 class=\"mb-0\">Current Bill Items</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div id=\"billItems\">\r\n");
      out.write("                            <div class=\"text-center py-4 text-muted\">\r\n");
      out.write("                                <i class=\"fas fa-shopping-cart fa-2x mb-2\"></i>\r\n");
      out.write("                                <p>No items added yet</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Bill Summary & Checkout -->\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <h5 class=\"mb-0\">Bill Summary</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div id=\"billSummary\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <strong>Total Items:</strong> <span id=\"totalItems\">0</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <strong>Subtotal:</strong> $<span id=\"subtotal\">0.00</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <strong>Tax (10%):</strong> $<span id=\"tax\">0.00</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <strong class=\"fs-5\">Total:</strong> $<span id=\"total\" class=\"fs-5\">0.00</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <form id=\"checkoutForm\" style=\"display: none;\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"paymentMethod\" class=\"form-label\">Payment Method</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"paymentMethod\" name=\"paymentMethod\" required>\r\n");
      out.write("                                    <option value=\"\">Select payment method</option>\r\n");
      out.write("                                    <option value=\"cash\">Cash</option>\r\n");
      out.write("                                    <option value=\"card\">Card</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-3\" id=\"cashAmountDiv\" style=\"display: none;\">\r\n");
      out.write("                                <label for=\"cashTendered\" class=\"form-label\">Cash Tendered</label>\r\n");
      out.write("                                <input type=\"number\" class=\"form-control\" id=\"cashTendered\" name=\"cashTendered\"\r\n");
      out.write("                                       step=\"0.01\" min=\"0\" placeholder=\"0.00\">\r\n");
      out.write("                                <div class=\"mt-1\">\r\n");
      out.write("                                    <small>Change: $<span id=\"changeAmount\">0.00</span></small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-success btn-lg w-100\" id=\"checkoutBtn\">\r\n");
      out.write("                                <i class=\"fas fa-credit-card me-2\"></i>Complete Sale\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("let billItems = [];\r\n");
      out.write("let itemCount = 0;\r\n");
      out.write("\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    loadAllProducts();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function formatPrice(price) {\r\n");
      out.write("    if (typeof price === 'number' && !isNaN(price)) {\r\n");
      out.write("        return price.toFixed(2);\r\n");
      out.write("    }\r\n");
      out.write("    return '0.00';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function formatPriceValue(price) {\r\n");
      out.write("    if (typeof price === 'number' && !isNaN(price)) {\r\n");
      out.write("        return price;\r\n");
      out.write("    }\r\n");
      out.write("    return 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function loadAllProducts() {\r\n");
      out.write("    fetch('");
      out.print( request.getContextPath() );
      out.write("/admin/products/search?q=')\r\n");
      out.write("        .then(response => {\r\n");
      out.write("            if (!response.ok) {\r\n");
      out.write("                throw new Error('Failed to load products');\r\n");
      out.write("            }\r\n");
      out.write("            return response.json();\r\n");
      out.write("        })\r\n");
      out.write("        .then(products => {\r\n");
      out.write("            displayProducts(products);\r\n");
      out.write("        })\r\n");
      out.write("        .catch(error => {\r\n");
      out.write("            document.getElementById('productResults').innerHTML = `\r\n");
      out.write("                <div class=\"alert alert-danger\">\r\n");
      out.write("                    <i class=\"fas fa-exclamation-circle me-2\"></i>\r\n");
      out.write("                    Error loading products: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error.message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            `;\r\n");
      out.write("        });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function displayProducts(products) {\r\n");
      out.write("    const resultsDiv = document.getElementById('productResults');\r\n");
      out.write("\r\n");
      out.write("    if (products.length === 0) {\r\n");
      out.write("        resultsDiv.innerHTML = `\r\n");
      out.write("            <div class=\"text-center py-4 text-muted\">\r\n");
      out.write("                <i class=\"fas fa-box-open fa-2x mb-2\"></i>\r\n");
      out.write("                <p>No products available</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        `;\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    let html = `\r\n");
      out.write("        <div class=\"table-responsive\">\r\n");
      out.write("            <table class=\"table table-striped table-hover\">\r\n");
      out.write("                <thead class=\"table-dark\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Code</th>\r\n");
      out.write("                        <th>Name</th>\r\n");
      out.write("                        <th>Price</th>\r\n");
      out.write("                        <th>Action</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("    `;\r\n");
      out.write("\r\n");
      out.write("    products.forEach(product => {\r\n");
      out.write("        html += `\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><code>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</code></td>\r\n");
      out.write("                <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                <td>$` + formatPrice(product.price) + `</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <button class=\"btn btn-primary btn-sm\" onclick=\"addItemToBill('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', formatPriceValue(product.price))\">\r\n");
      out.write("                        <i class=\"fas fa-plus me-1\"></i>Add\r\n");
      out.write("                    </button>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        `;\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    html += `\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("    `;\r\n");
      out.write("\r\n");
      out.write("    resultsDiv.innerHTML = html;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// Add item to bill (mock function)\r\n");
      out.write("function addItemToBill(productCode, productName, price, quantity = 1) {\r\n");
      out.write("    const existingItem = billItems.find(item => item.productCode === productCode);\r\n");
      out.write("    if (existingItem) {\r\n");
      out.write("        existingItem.quantity += quantity;\r\n");
      out.write("    } else {\r\n");
      out.write("        billItems.push({\r\n");
      out.write("            productCode: productCode,\r\n");
      out.write("            productName: productName,\r\n");
      out.write("            price: price,\r\n");
      out.write("            quantity: quantity\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    updateBillDisplay();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Remove item from bill\r\n");
      out.write("function removeItem(productCode) {\r\n");
      out.write("    billItems = billItems.filter(item => item.productCode !== productCode);\r\n");
      out.write("    updateBillDisplay();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Update bill display\r\n");
      out.write("function updateBillDisplay() {\r\n");
      out.write("    const billItemsDiv = document.getElementById('billItems');\r\n");
      out.write("    const checkoutForm = document.getElementById('checkoutForm');\r\n");
      out.write("\r\n");
      out.write("    if (billItems.length === 0) {\r\n");
      out.write("        billItemsDiv.innerHTML = `\r\n");
      out.write("            <div class=\"text-center py-4 text-muted\">\r\n");
      out.write("                <i class=\"fas fa-shopping-cart fa-2x mb-2\"></i>\r\n");
      out.write("                <p>No items added yet</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        `;\r\n");
      out.write("        checkoutForm.style.display = 'none';\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    let html = '';\r\n");
      out.write("    let subtotal = 0;\r\n");
      out.write("    let totalItems = 0;\r\n");
      out.write("\r\n");
      out.write("    billItems.forEach(item => {\r\n");
      out.write("        const itemTotal = item.price * item.quantity;\r\n");
      out.write("        subtotal += itemTotal;\r\n");
      out.write("        totalItems += item.quantity;\r\n");
      out.write("\r\n");
      out.write("        html += `\r\n");
      out.write("            <div class=\"d-flex justify-content-between align-items-center border-bottom py-2\">\r\n");
      out.write("                <div class=\"flex-grow-1\">\r\n");
      out.write("                    <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong><br>\r\n");
      out.write("                    <small class=\"text-muted\">Code: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" | $");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.price.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('x');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</small>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"text-end\">\r\n");
      out.write("                    <div class=\"fw-bold\">$");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemTotal.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    <button class=\"btn btn-sm btn-outline-danger mt-1\" onclick=\"removeItem('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.productCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\">\r\n");
      out.write("                        <i class=\"fas fa-times\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        `;\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    billItemsDiv.innerHTML = html;\r\n");
      out.write("\r\n");
      out.write("    const tax = subtotal * 0.10;\r\n");
      out.write("    const total = subtotal + tax;\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('totalItems').textContent = totalItems;\r\n");
      out.write("    document.getElementById('subtotal').textContent = subtotal.toFixed(2);\r\n");
      out.write("    document.getElementById('tax').textContent = tax.toFixed(2);\r\n");
      out.write("    document.getElementById('total').textContent = total.toFixed(2);\r\n");
      out.write("\r\n");
      out.write("    checkoutForm.style.display = 'block';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Clear bill\r\n");
      out.write("function clearBill() {\r\n");
      out.write("    if (billItems.length > 0 && confirm('Are you sure you want to clear the current bill?')) {\r\n");
      out.write("        billItems = [];\r\n");
      out.write("        updateBillDisplay();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Payment method change\r\n");
      out.write("document.getElementById('paymentMethod').addEventListener('change', function() {\r\n");
      out.write("    const cashDiv = document.getElementById('cashAmountDiv');\r\n");
      out.write("    const cashInput = document.getElementById('cashTendered');\r\n");
      out.write("\r\n");
      out.write("    if (this.value === 'cash') {\r\n");
      out.write("        cashDiv.style.display = 'block';\r\n");
      out.write("        cashInput.required = true;\r\n");
      out.write("    } else {\r\n");
      out.write("        cashDiv.style.display = 'none';\r\n");
      out.write("        cashInput.required = false;\r\n");
      out.write("        cashInput.value = '';\r\n");
      out.write("        document.getElementById('changeAmount').textContent = '0.00';\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// Cash tendered calculation\r\n");
      out.write("document.getElementById('cashTendered').addEventListener('input', function() {\r\n");
      out.write("    const tendered = parseFloat(this.value) || 0;\r\n");
      out.write("    const total = parseFloat(document.getElementById('total').textContent) || 0;\r\n");
      out.write("    const change = Math.max(0, tendered - total);\r\n");
      out.write("    document.getElementById('changeAmount').textContent = change.toFixed(2);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// Form submission\r\n");
      out.write("document.getElementById('checkoutForm').addEventListener('submit', function(e) {\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("    if (billItems.length === 0) {\r\n");
      out.write("        alert('No items in the bill');\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    const paymentMethod = document.getElementById('paymentMethod').value;\r\n");
      out.write("    if (!paymentMethod) {\r\n");
      out.write("        alert('Please select a payment method');\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    let cashTendered = 0;\r\n");
      out.write("    if (paymentMethod === 'cash') {\r\n");
      out.write("        cashTendered = parseFloat(document.getElementById('cashTendered').value) || 0;\r\n");
      out.write("        const total = parseFloat(document.getElementById('total').textContent) || 0;\r\n");
      out.write("\r\n");
      out.write("        if (cashTendered < total) {\r\n");
      out.write("            alert('Cash tendered is less than the total amount');\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("    } else {\r\n");
      out.write("        // For card payment, assume full amount is tendered\r\n");
      out.write("        cashTendered = parseFloat(document.getElementById('total').textContent) || 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    const checkoutBtn = document.getElementById('checkoutBtn');\r\n");
      out.write("    const originalText = checkoutBtn.innerHTML;\r\n");
      out.write("    checkoutBtn.innerHTML = '<i class=\"fas fa-spinner fa-spin me-2\"></i>Processing...';\r\n");
      out.write("    checkoutBtn.disabled = true;\r\n");
      out.write("\r\n");
      out.write("    const billRequest = {\r\n");
      out.write("        items: billItems.map(item => ({\r\n");
      out.write("            productCode: item.productCode,\r\n");
      out.write("            quantity: item.quantity\r\n");
      out.write("        })),\r\n");
      out.write("        cashTendered: cashTendered\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    fetch('");
      out.print( request.getContextPath() );
      out.write("/billing/create', {\r\n");
      out.write("        method: 'POST',\r\n");
      out.write("        headers: {\r\n");
      out.write("            'Content-Type': 'application/json',\r\n");
      out.write("        },\r\n");
      out.write("        body: JSON.stringify(billRequest)\r\n");
      out.write("    })\r\n");
      out.write("    .then(response => {\r\n");
      out.write("        if (!response.ok) {\r\n");
      out.write("            return response.json().then(err => { throw new Error(err.error || 'Failed to create bill'); });\r\n");
      out.write("        }\r\n");
      out.write("        return response.json();\r\n");
      out.write("    })\r\n");
      out.write("    .then(data => {\r\n");
      out.write("        alert(`Bill created successfully!\\nSerial Number: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.serialNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\nTotal: $");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.totalAmount.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\nCash Tendered: $");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.cashTendered.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\\nChange: $");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data.changeReturned.toFixed(2)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("        clearBill();\r\n");
      out.write("    })\r\n");
      out.write("    .catch(error => {\r\n");
      out.write("        alert('Error creating bill: ' + error.message);\r\n");
      out.write("    })\r\n");
      out.write("    .finally(() => {\r\n");
      out.write("        checkoutBtn.innerHTML = originalText;\r\n");
      out.write("        checkoutBtn.disabled = false;\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    </div> <!-- End container-fluid -->\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"bg-dark text-light mt-5 py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <h5>SYOS</h5>\r\n");
      out.write("                    <p class=\"mb-0\">Supermarket Billing System</p>\r\n");
      out.write("                    <small class=\"text-muted\">Efficient inventory and billing management</small>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-md-end\">\r\n");
      out.write("                    <p class=\"mb-0\">&copy; 2024 SYOS System. All rights reserved.</p>\r\n");
      out.write("                    <small class=\"text-muted\">Version 1.0.0</small>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
